### PR TITLE
fix(ci): bump CI Node.js to 24 to restore npm 11 trusted publishing

### LINKED ISSUE #2397: CLI release workflow fails at `npm install -g npm@11` step
### Steps to Reproduce:
1. Wait for the scheduled `CLI - Automated Release` workflow to run (Mon/Wed 07:30 GMT), or trigger it manually via `workflow_dispatch`.
2. Observe the `analyze` job fail at the `Update to npm 11` step (`.github/workflows/automated-release.yml:56-57`).

### Expected Result:
The workflow proceeds past `Update to npm 11`, evaluates whether a release is due, and (when there are releasable changes on `main`) opens an automated version-bump PR. Merging that PR publishes a new `@finos/calm-cli` version to npm.

### Actual Result:
The `Update to npm 11` step fails on every run. Example failure (run [25098279438](https://github.com/finos/architecture-as-code/actions/runs/25098279438/job/73540498734), 2026-04-29):

```
Run npm install -g npm@11
npm error code MODULE_NOT_FOUND
npm error Cannot find module 'promise-retry'
npm error Require stack:
npm error - /opt/hostedtoolcache/node/22.22.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js
npm error - /opt/hostedtoolcache/node/22.22.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/index.js
npm error - /opt/hostedtoolcache/node/22.22.2/x64/lib/node_modules/npm/lib/commands/install.js
...
##[error]Process completed with exit code 1.
```

The same step appears four times in `automated-release.yml` (lines 56, 247, 396, 465) and four times in `automated-release-calm-server.yml` (lines 56, 243, 392, 461). The CALM Server release workflow is affected by the same root cause.

The `CLI - Automated Release` workflow has failed on every scheduled run since at least 2026-04-15:

| Run | Date |
|---|---|
| 25098279438 | 2026-04-29 |
| 24984214205 | 2026-04-27 |
| 24767539155 | 2026-04-22 |
| 24655949112 | 2026-04-20 |
| 24443562903 | 2026-04-15 |

As a side effect, the merged docify dependency fix from PR #2324 has been blocked from reaching npm, leaving issues such as #2384 reproducible against the published 1.37.0 CLI even though the fix is on `main`.

### Environment:
- Workflow files: `.github/workflows/automated-release.yml`, `.github/workflows/automated-release-calm-server.yml`
- Runner: `ubuntu-latest` (GitHub-hosted)
- Node: 22.22.2 (from `actions/setup-node@v6` with `node-version: 22`)
- Bundled npm: 10.9.7
- Failing command: `npm install -g npm@11`

### Additional Context:
The `npm install -g npm@11` step was introduced in PR #2207 (commit `a42d234d`, 2026-03-02) "to ensure compatibility with npm 11... and the latest npm features". No specific feature was named.

The global upgrade is no longer required:
- `package.json` already overrides `@semantic-release/npm` to bundle `npm@11.12.1`, so semantic-release uses npm 11 internally regardless of the global version.
- `npm publish --provenance` (used in the publish step) is supported by npm 9.5+, so the bundled `npm@10.9.7` is sufficient.
- `build-cli.yml` and `build-shared.yml` do not perform this upgrade and run successfully.

The root cause is a known regression in the npm 10.9.7 → 11 self-upgrade path that ships with Node 22.22.x, where `@npmcli/arborist`'s bundled dependencies become unresolvable mid-install.

### PR DESCRIPTION
**Pull request by rocketstack-matt**
## Description

Bumps the Node.js version pinned in every CI workflow from 22 to 24 to restore npm Trusted Publishing (OIDC), which has been silently broken since #2397 was merged.

### Root cause

`@finos/calm-cli@1.39.0` did not publish to npm on 2026-05-02 (run [25255770432](https://github.com/finos/architecture-as-code/actions/runs/25255770432)). The `Publish to NPM` step failed with:

```
npm error code E404
npm error 404 Not Found - PUT https://registry.npmjs.org/@finos%2fcalm-cli - Not found
npm error 404 '@finos/calm-cli@1.39.0' is not in this registry.
```

This is npm's masked-403 response when the auth identity is not authorized to publish a scoped package. Querying the registry confirms the last successful publish (1.37.0, 2026-04-01) used Trusted Publishing rather than the bearer token:

```
$ npm view @finos/calm-cli
_npmUser: GitHub Actions <npm-oidc-no-reply@github.com>
```

OIDC trusted publishing requires npm 11.5+. Node 22.22.x ships npm 10.9.7, so since #2397 removed the `npm install -g npm@11` step the publish job has been quietly falling back to bearer-token auth.

### Why Node 24 (not re-add the global upgrade)

The `npm install -g npm@11` step was removed in #2397 because it crashed mid-install on Node 22 with `Cannot find module 'promise-retry'` - a known regression in npm 10.9.7's self-upgrade path. Reintroducing it would flip back to the previously-broken state. Node 24 ships npm 11 in-the-box, ending the cycle.

Other notes:
- Root `package.json` already declares `node: \"^22.14.0 || >=24.10.0\"`, so no engines change is required.
- Per-workspace engines fields (`docs`, `calm-suite/calm-studio`, `calm-suite/calm-studio/docs-site`, `calm-suite/calm-guard/docs`) all accept `>=20`.
- Node 22 reaches EOL in April 2027; Node 24 is the current Active LTS line.

### Normalization

While here, the mix of `node-version: v22`, `22`, `'22'`, and `['22.x']` across 21 workflow files has been normalized to a single `node-version: 24` (matrix entry kept as `['24.x']`).

## Type of Change
- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🔧 Chore (maintenance, dependencies, CI, etc.)

## Affected Components
- [x] CI/CD

## Testing
- [x] I have tested my changes locally
- [ ] I have added/updated unit tests
- [ ] All existing tests pass

CI on this PR will exercise every affected workflow. To fully verify the publish path, after merge the next `cli-v1.x.x` release run should show `_npmUser: GitHub Actions <npm-oidc-no-reply@github.com>` again on the published version. Recommend cutting `cli-v1.39.1` to re-exercise the path - the `cli-v1.39.0` git tag and GitHub Release already exist (publish silently dropped at the npm step), and a patch release is cleaner than retrofit-publishing the same version.

## Checklist
- [x] My commits follow the [conventional commit format](https://www.conventionalcommits.org/)
- [x] I have updated documentation if necessary
- [ ] I have added tests for my changes (if applicable)
- [x] My changes follow the project's coding standards

## Related

Re-fixes #2397 (the previous fix's premise that the global npm 11 upgrade was unnecessary turned out to be incorrect).

### CODE REVIEW

File: .github/workflows/automated-release.yml [hunk 1]
```diff
@@ -450,7 +450,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
         with:
-          node-version: 22
+          node-version: 24
```
[the remark this answers is not in the document]
Comment (rocketstack-matt) [reply .github/workflows/automated-release.yml:453]: Thanks - acknowledged but not making the change.

`actions/setup-node@v6` with `node-version: 24` resolves to the latest 24.x in the GitHub-hosted runner toolcache, which on `ubuntu-latest` is well above 24.10 today. There is no realistic resolution path to an earlier 24.x minor on hosted runners. Node 24.0.0 already shipped with npm 11.3 and 24.10 ships npm 11.5+, so Trusted Publishing is satisfied at the floor regardless.

Pinning only the publish jobs to `24.10.x` would also create a drift between the publish toolchain and the build/test toolchain that produces the artifact we publish, which feels worse than the theoretical reproducibility win.

File: .github/workflows/automated-release-calm-server.yml [hunk 2]
```diff
@@ -446,7 +446,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
         with:
-          node-version: 22
+          node-version: 24
```
[the remark this answers is not in the document]
Comment (rocketstack-matt) [reply .github/workflows/automated-release-calm-server.yml:449]: Thanks - acknowledged but not making the change.

`actions/setup-node@v6` with `node-version: 24` resolves to the latest 24.x in the GitHub-hosted runner toolcache, which on `ubuntu-latest` is well above 24.10 today. There is no realistic resolution path to an earlier 24.x minor on hosted runners. Node 24.0.0 already shipped with npm 11.3 and 24.10 ships npm 11.5+, so Trusted Publishing is satisfied at the floor regardless.

Pinning only the publish jobs to `24.10.x` would also create a drift between the publish toolchain and the build/test toolchain that produces the artifact we publish, which feels worse than the theoretical reproducibility win.

**Comment by rocketstack-matt** [comment]
@markscott-ms can you please take a look if you get a min

**Review by LeighFinegold — APPROVED** [review]
